zuul:
  routes:
    users:
      path: /user/**
      serviceId: fantacalcio-user
      stripPrefix: false
      sensitiveHeaders:
    auth:
      path: /uaa/**
      serviceId: fantacalcio-auth-server
      stripPrefix: false
      sensitiveHeaders:
  prefix: /api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
