zuul:
  routes:
    users:
      path: /user/**
      serviceId: fantacalcio-user
      stripPrefix: true
      sensitiveHeaders:
    auth:
      path: /auth/**
      serviceId: fantacalcio-auth-server
      stripPrefix: true
      sensitiveHeaders:
  prefix: /api